### ISSUE TITLE
Strip whitespace from project status field data

### ISSUE THREAD

**Issue by stdavis** [agrc/wri-webapi#1]
So that the css classes in https://github.com/agrc/wri-web/blob/master/src/app/project/templates/ProjectDetails.html#L3
will work with Aaron's classes below:

``` css
#projectStatus-Draft {background:#838e8e;} /* Draft - Gray */
#projectStatus-Proposed {background:#AF4925;} /* Proposed - Orange */
#projectStatus-Current {background:#2191AE;} /* Current - Blue */
#projectStatus-PendingCompleted {background:#CC9F2B;} /* Pending-Completed - Yellow */
#projectStatus-Completed {background:#269345;} /* Completed - Green */
#projectStatus-Cancelled{background:#000000;} /* Cancelled - Black */
```

Specifically looking at Pending Completed.
